### ISSUE TITLE
Truss push failed, Unable to find image

### ISSUE THREAD

**Issue by studentofcoding** [basetenlabs/truss#1070]
**Describe the bug**
When running truss push, it always failed to build Image `Unable to find image. Proceeding to build.`

```
Aug 05 07:52:53pm Unable to find image. Proceeding to build.
Aug 05 07:52:54pm Building image...
Aug 05 07:52:54pm Endpoint open: buildkitd-4.buildkitd.baseten-tekton.svc.cluster.local:1234
Aug 05 07:52:54pm error: listing workers for Build: failed to list workers: Unavailable: connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"
Aug 05 07:52:55pm 2024/08/05 12:52:55 Skipping step because a previous step failed
```

**To Reproduce**
- run `truss push` with these config.yaml
```
base_image:
  image: bolabaseten/comfyui-truss-base:6a7bc35
  python_executable_path: /usr/bin/python3
build_commands:
- git clone https://github.com/comfyanonymous/ComfyUI.git
- cd ComfyUI && git checkout b1fd26fe9e55163f780bf9e5f56bf9bf5f035c93 && pip install -r requirements.txt
- cd ComfyUI/custom_nodes && git clone https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus.git
- cd ComfyUI/custom_nodes && git clone https://github.com/cubiq/ComfyUI_IPAdapter_plus.git
- cd ComfyUI/models/checkpoints && wget -O juggernautXL_v9Rdphoto2Lightning.safetensors https://civitai.com/api/download/models/357609?type=Model&format=SafeTensor&size=full&fp=fp16
- cd ComfyUI/models/photomaker && wget -O photomaker-v2.bin https://huggingface.co/TencentARC/PhotoMaker-V2/resolve/main/photomaker-v2.bin
description: Deploy a ComfyUI workflow as a Truss
environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input:
    workflow_values:
      image_input_1: image_2
      image_input_2: image_1
      negative_prompt: photograph of a man img, see at viewer, looking professional
      positive_prompt: text, watermark
model_name: ComfyUI Workflow Professional Image to Image
python_version: py311
requirements:
- websocket-client==1.6.4
- accelerate==0.23.0
- opencv-python
resources:
  accelerator: A10G
  cpu: '2'
  memory: 14Gi
  use_gpu: true
secrets: {}
system_packages:
- ffmpeg
- libgl1-mesa-glx
```

**Expected behavior**
It should run as intended

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.
<img width="1403" alt="Screenshot 2024-08-05 at 19 56 39" src="https://github.com/user-attachments/assets/098250fb-28c2-40df-8692-f10bd5f2140b">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] MacOs 15
 - Environment versions [e.g. python versions, framework/package versions] Python 3.11
 - Truss version [e.g. 22] truss, version 0.9.26

**Additional context**
Nothing
