### ISSUE TITLE
Simplify the generated default configuration

### ISSUE THREAD

**Issue by joostinyi** [basetenlabs/truss#383]
**Description**
Upon first use of `truss` users will often run `truss init` to create an empty truss to start developing on. Currently, we naively write all the properties of the `TrussConfig` object to the generated `config.yaml` which can be overwhelming for first users. We should look to simplify the generated config in order to make this first experience better.

**Solution**
The current generated config is as follows:
```
base_image: null
bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
examples_filename: examples.yaml
external_package_dirs: []
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: null
model_type: custom
python_version: py39
requirements: []
resources:
  accelerator: null
  cpu: 500m
  memory: 512Mi
  use_gpu: false
secrets: {}
spec_version: '2.0'
system_packages: []
train:
  resources:
    accelerator: null
    cpu: 500m
    memory: 512Mi
    use_gpu: false
  training_class_filename: train.py
  training_class_name: Train
  training_module_dir: train
  variables: {}
```
We should look to reduce the config to the settings that our users interact with most:
```
environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: null
python_version: py39
requirements: []
resources:
  accelerator: null
  cpu: 500m
  memory: 512Mi
  use_gpu: false
secrets: {}
system_packages: []
```
